version: "3.1"
services:
    api:
        build:
            context: ./api
            dockerfile: dev.Dockerfile
        container_name: better_izivi_api
        volumes:
            - ./api:/api
        working_dir: /api
        command: "rails server -p 8000 -b 0.0.0.0"
        depends_on:
            - mysql
        ports:
            - "28000:8000"
        environment:
            - DATABASE_HOST=mysql
            - DATABASE_USERNAME=root
            - DATABASE_PASSWORD=
            - DEVISE_JWT_SECRET_KEY=verysecret
            - DEVISE_SECRET_KEY=verysecret
            - COMMUNITY_PASSWORD=123456
            - PAIN_CREDITOR_NAME=Example Company
            - PAIN_CREDITOR_BIC=POFICHBEXXX
            - PAIN_CREDITOR_IBAN=CH9300762011623852957
            - MAIL_SENDER=no-reply@stiftungswo.ch
            - SMTP_HOST=example.com
            - SMTP_PORT=25
            - SMTP_USER_NAME=username
            - SMTP_PASSWORD=password
            - SERVICE_AGREEMENT_LETTER_SENDER_NAME=My Company Name
            - SERVICE_AGREEMENT_LETTER_SENDER_ADDRESS=MyStreet 111
            - SERVICE_AGREEMENT_LETTER_SENDER_ZIP_CITY=1234 MyCity
            - FEEDBACK_MAIL_SURVEY_URL="e.g. http://survey.stiftungswo.ch/my/survey?service_id=%{service_id}"
            - FEEDBACK_MAIL_TESTIMONIAL_URL="https://naturzivi.ch/testimonial"
            - PASSWORD_RESET_LINK="e.g. http://izivi.localhost:3000/users/passwords/edit/%{token}"

    frontend:
        image: node:10
        container_name: better_izivi_frontend
        volumes:
            - ./frontend:/var/frontend:cached
        working_dir: /var/frontend
        ports:
            - "23000:3000"
        command: bash -c "yarn install && yarn run start"

    mysql:
        image: mariadb:10.3.14
        container_name: better_izivi_db
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "23306:3306"
        volumes:
            - ./database:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: better_izivi_phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        ports:
            - 28080:80
