# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.4.10'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'bootsnap', '>= 1.1.0', require: false
gem 'devise'
gem 'devise-jwt', '~> 0.13.0'
gem 'docx'
gem 'dotenv-rails'
gem 'hexapdf'
gem 'iban-tools'
gem 'jbuilder'
# Ruby 3.4 dropped `matrix`, `observer` and `ostruct` from the default gems
# bundled with the interpreter. `matrix` and `observer` are hard LoadErrors
# for transitive deps (prawn and factory_bot_rails respectively); `ostruct`
# is just to silence a "will no longer be part of the default gems" warning
# ahead of Ruby 4.0.
gem 'matrix'
gem 'mysql2', '>= 0.4.4', '< 0.6.0'
gem 'observer'
gem 'ostruct'
gem 'pdf-forms'
gem 'prawn'
gem 'prawn-table'
gem 'puma'
gem 'rack-cors', require: 'rack/cors'
gem 'rails', '8.0.5'
gem 'rails-i18n'
gem 'sepa_king'
gem 'sidekiq', '~> 8.1'
gem 'sidekiq-cron', '~> 2.4'
gem 'validates_timeliness'

group :production do
  gem 'lograge'
  gem 'sentry-rails', '~> 6.6'
  gem 'sentry-ruby', '~> 6.6'
end

group :development, :test do
  gem 'brakeman', require: false
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rake', '13.0.6'
  gem 'reek'
  gem 'rspec-collection_matchers'
  gem 'rspec-rails', '~> 8.0'
  gem 'rubocop', '~> 1.88', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', '~> 2.36', require: false
  gem 'rubocop-rspec', '~> 3.10', require: false
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'bullet'
  gem 'letter_opener'
  gem 'listen', '>= 3.0.5', '< 3.8'
  # Ruby 3.4 dropped `mutex_m` from the default gems bundled with the
  # interpreter; spring-watcher-listen still requires it.
  gem 'mutex_m'
  # Ruby 3.4 dropped `kconv` from the default gems bundled with the
  # interpreter; letter_opener still requires it. The `nkf` gem ships the
  # same lib/kconv.rb shim, so pulling it in restores `require 'kconv'`.
  gem 'nkf'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'climate_control'
  gem 'i18n-tasks', '~> 1.1'
  gem 'pdf-inspector', require: 'pdf/inspector'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
  gem 'test-prof', '~> 1.6'
end

gem 'tzinfo-data'
