# frozen_string_literal: true

source 'https://rubygems.org'

ruby File.read(File.join(__dir__, '.ruby-version')).strip

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'bootsnap', '>= 1.1.0', require: false
gem 'devise'
gem 'devise-jwt', '~> 0.9.0'
gem 'dotenv-rails'
gem 'hexapdf'
gem 'iban-tools'
gem 'jbuilder'
gem 'matrix'
gem 'mysql2', '>= 0.4.4', '< 0.6.0'
gem 'pdf-forms'
gem 'prawn'
gem 'prawn-table'
gem 'puma', '~> 5.6'
gem 'rack-cors', require: 'rack/cors'
gem 'rails', '= 7.0.3.1'
gem 'rails-i18n'
gem 'sepa_king'
gem 'sidekiq', '~> 6.4'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'validates_timeliness'

group :production do
  gem 'lograge'
  gem 'sentry-raven'
end

group :development, :test do
  gem 'brakeman', require: false
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rake'
  gem 'reek'
  gem 'rspec-collection_matchers'
  gem 'rspec-rails', '~> 5.1.2'
  gem 'rubocop', '~> 1.18', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', '~> 2.11'
  gem 'rubocop-rspec', '~> 2.4', require: false
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'bullet'
  gem 'letter_opener'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen'
end

group :test do
  gem 'climate_control'
  gem 'i18n-tasks', '~> 0.9.29'
  gem 'pdf-inspector', require: 'pdf/inspector'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
  gem 'test-prof'
end
